name: Build to branch
description: Build source branch and update release branch containing only built/release files.

inputs:
  source_branch:
    description: Name of source branch.
    default: main
  release_branch:
    description: Name of target release branch.
    default: release
  build_script:
    description: Command to run to build code. "npm ci; npm run build" by default.
    default: |
      npm ci
      npm run build
    required: false
  built_asset_paths:
    description: Paths or directories to include in the release branch (built assets)
    required: true
  extra_files:
    description: Optional extra files from the source branch to include (e.g., README.md, LICENSE.md)
    default: ""
    required: false
  commit_user_name:
    description: Name to use for release branch commit author.
    default: "Your friendly neighborhood GH Actions Bot"
    required: false
  commit_user_email:
    description: Email to use for release branch commit email.
    default: "<>"
    required: false

runs:
  using: composite

  steps:
    - name: Configure git
      shell: bash
      run: |
        git config user.name "${{ inputs.commit_user_name }}"
        git config user.email "${{ inputs.commit_user_email }}"

    - name: Checkout source branch
      uses: actions/checkout@v5
      with:
        ref: ${{ inputs.source_branch }}
        fetch-depth: 0

    - name: Run build
      shell: bash
      run: ${{ inputs.build_script }}

    - name: Checkout or create release branch
      shell: bash
      run: |
        git fetch origin ${{ inputs.release_branch }} || true
        if git rev-parse --verify origin/${{ inputs.release_branch }} >/dev/null 2>&1; then
          git checkout ${{ inputs.release_branch }}
        else
          git checkout --orphan ${{ inputs.release_branch }}
        fi

        # Remove all tracked files
        git rm -r --cached . || true

        # Remove all files except .git
        find . -mindepth 1 -maxdepth 1 ! -name ".git" -exec rm -rf {} +

    - name: Copy built assets to release branch
      shell: bash
      run: |
        shopt -s dotglob nullglob
        for path in ${{ inputs.built_asset_paths }}; do
          if [ -e "$path" ]; then
            cp -r "$path" .
          else
            echo "Warning: built asset path '$path' does not exist."
          fi
        done

    - name: Copy extra files (optional)
      shell: bash
      run: |
        if [ -n "${{ inputs.extra_files }}" ]; then
          shopt -s dotglob nullglob
          for f in ${{ inputs.extra_files }}; do
            if [ -e "$f" ]; then
              cp -r "$f" .
            else
              echo "Warning: extra file '$f' does not exist."
            fi
          done
        fi

    - name: Commit and push release
      shell: bash
      run: |
        git add .
        git commit -m "Build release from ${{ inputs.source_branch }}#$(git rev-parse --short ${{ inputs.source_branch }})" || echo "Nothing to commit"
        git push origin ${{ inputs.release_branch }}:${{ inputs.release_branch }}
