name: Build to branch
description: Build source branch and update release branch containing only exported files (respects .gitattributes export-ignore).

inputs:
  source_branch:
    description: Name of source branch.
    default: main
  release_branch:
    description: Name of target release branch.
    default: release
  build_script:
    description: Command to run to build code. "npm ci; npm run build" by default.
    default: |
      npm ci
      npm run build
    required: false
  commit_user_name:
    description: Name to use for release branch commit author.
    default: "Your friendly neighborhood GH Actions Bot"
    required: false
  commit_user_email:
    description: Email to use for release branch commit email.
    default: "<>"
    required: false

runs:
  using: composite

  steps:
    - name: Configure git
      shell: bash
      run: |
        git config user.name "${{ inputs.commit_user_name }}"
        git config user.email "${{ inputs.commit_user_email }}"

    - name: Checkout source branch
      uses: actions/checkout@v5
      with:
        ref: ${{ inputs.source_branch }}
        fetch-depth: 0

    - name: Build code
      shell: bash
      run: ${{ inputs.build_script }}

    - name: Create export archive (respects .gitattributes)
      shell: bash
      run: |
        mkdir -p /tmp/export
        git archive --format=tar HEAD > /tmp/export/export.tar

    - name: Checkout or create release branch
      shell: bash
      run: |
        git fetch origin ${{ inputs.release_branch }} || true
        if git rev-parse --verify origin/${{ inputs.release_branch }} >/dev/null 2>&1; then
          git checkout ${{ inputs.release_branch }}
        else
          git checkout --orphan ${{ inputs.release_branch }}
        fi

        # Remove all tracked files
        git rm -r --cached . || true

        # Remove all files except .git
        find . -mindepth 1 -maxdepth 1 ! -name ".git" -exec rm -rf {} +

    - name: Extract exported files into release branch
      shell: bash
      run: |
        mkdir tmp_export
        tar -xf /tmp/export/export.tar -C tmp_export
        # Safely copy files including hidden ones
        shopt -s dotglob nullglob
        cp -r tmp_export/* .
        rm -rf tmp_export /tmp/export/export.tar

    - name: Commit and push release
      shell: bash
      run: |
        git add .
        git commit -m "Build release from ${{ inputs.source_branch }}#$(git rev-parse --short ${{ inputs.source_branch }})" || echo "Nothing to commit"
        git push origin ${{ inputs.release_branch }}:${{ inputs.release_branch }}
