name: Build to branch
description: Merge and build a source branch into a releasable, fully-built branch. Maintains branch history and force-commits gitignore'd built files.

inputs:
  source_branch:
    description: Name of source branch.
    default: main

  release_branch:
    description: Name of target release branch. Will be updated with a merge commit including built code.
    default: release

  built_asset_paths:
    description: Generated assets to forcibly include in release branch commit. Overrides .gitignore.
    required: true

  build_script:
    description: Command to run to build code. "npm ci; npm run build" by default.
    default: |
      npm ci --ignore-scripts
      npm run build
    required: false

  php_version:
    description: PHP version to install via setup-php.
    default: '8.3'
    required: false

  php_extensions:
    description: Additional PHP extensions to enable (comma-separated list).
    default: ''
    required: false

  php_ini_values:
    description: Extra php.ini values (comma-separated key=value pairs).
    default: ''
    required: false

  run_composer_install:
    description: Set to true to run composer install.
    default: 'false'
    required: false

  composer_script:
    description: Command to run to install Composer dependencies. "composer install" by default.
    default: |
      composer install --no-dev --no-interaction --prefer-dist --no-progress --optimize-autoloader
    required: false

  commit_user_name:
    description: Name to use for release branch commit author.
    default: "Your friendly neighborhood GH Actions Bot"
    required: false

  commit_user_email:
    description: Email to use for release branch commit email.
    default: "<>"
    required: false

runs:
  using: composite

  steps:
    - name: Configure git
      shell: bash
      run: |
        git config user.name "${{ inputs.commit_user_name }}"
        git config user.email "${{ inputs.commit_user_email }}"

    - name: Check out release branch
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        ref: ${{ inputs.release_branch }}
        fetch-depth: 0

    - name: Merge source into release branch
      shell: bash
      # Simulate "-s theirs", which doesn't exist in git for sensible reasons
      # which do not apply to our current situation.
      # https://web.archive.org/web/20131126171744/http://www.seanius.net/blog/2011/02/git-merge-s-theirs/
      run: |
        git fetch origin '${{ inputs.source_branch }}'
        git fetch origin '${{ inputs.release_branch }}'
        git checkout '${{ inputs.source_branch }}'
        git checkout '${{ inputs.release_branch }}'
        git merge -s ours '${{ inputs.source_branch }}'
        git diff --binary '${{ inputs.source_branch }}' | git apply -R --index
        git commit --amend -m "Merge branch '${{ inputs.source_branch }}' into '${{ inputs.release_branch }}'"

    - name: Set up PHP
      if: ${{ inputs.run_composer_install == 'true' }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php_version }}
        extensions: ${{ inputs.php_extensions }}
        ini-values: ${{ inputs.php_ini_values }}
        coverage: none

    - name: Composer install
      if: ${{ inputs.run_composer_install == 'true' }}
      shell: bash
      run: ${{ inputs.composer_script }}

    - name: Build code
      shell: bash
      run: ${{ inputs.build_script }}

    - name: Update release branch (remove export-ignore files)
      shell: bash
      run: |
        if [ -f .gitattributes ]; then
          grep 'export-ignore' .gitattributes | while read -r line; do
            path="${line%% *}"       # extract path before space
            path="${path#/}"         # remove leading slash

            if [ "$path" = ".*" ]; then
              # special handling for root dotfiles
              for dotfile in .[^.]*; do
                # skip .git
                [ "$dotfile" = ".git" ] && continue
                if [ -e "$dotfile" ]; then
                  echo "Removing dotfile $dotfile as marked by .gitattributes"
                  git rm -rf "$dotfile" || true
                fi
              done
            else
              if [ -e "$path" ]; then
                echo "Removing $path as marked by .gitattributes"
                git rm -rf "$path" || true
              fi
            fi
          done
        fi

        if [ -d vendor ]; then
          echo "Adding vendor directory"
          git add -f vendor
        fi

        # Re-add built assets (they may have been removed)
        git add -f ${{ inputs.built_asset_paths }}

        git commit --amend -m "Build to '${{ inputs.release_branch }}' from ${{ inputs.source_branch }}#$( git rev-parse --short ${{ inputs.source_branch }} )"
        git push origin '${{ inputs.release_branch }}':'${{ inputs.release_branch }}'
