name: Lint Suite
description: Run PHPCS, ESLint, and Stylelint with shared defaults tuned for WordPress projects.

inputs:
  working-directory:
    description: Optional path to run commands from.
    default: .
    required: false

  php-version:
    description: PHP version to install via setup-php.
    default: '8.3'
    required: false

  php-extensions:
    description: Additional PHP extensions to enable (comma-separated list).
    default: ''
    required: false

  php-ini-values:
    description: Extra php.ini values (comma-separated key=value pairs).
    default: ''
    required: false

  composer-install:
    description: Whether to run composer install before linting.
    default: 'true'
    required: false

  composer-args:
    description: Arguments passed to composer install.
    default: '--no-interaction --prefer-dist --no-progress'
    required: false

  composer-cache-key:
    description: Optional cache key suffix for composer dependencies.
    default: ''
    required: false

  npm-install:
    description: Whether to install Node dependencies via npm.
    default: 'true'
    required: false

  npm-install-command:
    description: Command used to install Node dependencies (e.g. npm ci).
    default: 'npm ci'
    required: false

  node-version:
    description: Node.js version to provision via setup-node.
    default: '24'
    required: false

  npm-cache-key:
    description: Optional cache key suffix for Node dependencies.
    default: ''
    required: false

  phpcs-bin:
    description: Path to the PHPCS executable.
    default: 'vendor/bin/phpcs'
    required: false

  phpcs-standard:
    description: Coding standard passed to PHPCS (leave empty to rely on project ruleset discovery).
    default: ''
    required: false

  phpcs-args:
    description: Additional PHPCS arguments.
    default: '--report=full'
    required: false

  phpcs-paths:
    description: Space-separated list of paths to scan with PHPCS.
    default: '.'
    required: false

  run-phpcs:
    description: Set to false to skip PHPCS execution.
    default: 'true'
    required: false

  eslint-bin:
    description: Command used to invoke ESLint.
    default: 'npx eslint'
    required: false

  eslint-args:
    description: Extra arguments for ESLint.
    default: '--max-warnings=0'
    required: false

  eslint-paths:
    description: Space-separated list of paths to lint with ESLint.
    default: 'src/**/*.{js,jsx,ts,tsx}'
    required: false

  run-eslint:
    description: Set to false to skip ESLint execution.
    default: 'true'
    required: false

  stylelint-bin:
    description: Command used to invoke Stylelint.
    default: 'npx stylelint'
    required: false

  stylelint-args:
    description: Extra arguments for Stylelint.
    default: ''
    required: false

  stylelint-paths:
    description: Space-separated list of paths to lint with Stylelint.
    default: 'src/**/*.{scss,css}'
    required: false

  run-stylelint:
    description: Set to false to skip Stylelint execution.
    default: 'true'
    required: false

runs:
  using: composite
  steps:
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        extensions: ${{ inputs.php-extensions }}
        ini-values: ${{ inputs.php-ini-values }}
        coverage: none

    - name: Detect Node dependency files
      id: node-lock
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        WORKING_DIR: ${{ inputs.working-directory }}
      run: |
        set -eo pipefail

        paths=()
        for file in package-lock.json npm-shrinkwrap.json; do
          if [[ -f "$file" ]]; then
            if [[ "$WORKING_DIR" == '.' ]]; then
              paths+=("$file")
            else
              paths+=("$WORKING_DIR/$file")
            fi
          fi
        done

        if (( ${#paths[@]} )); then
          {
            echo "paths<<EOF"
            printf '%s\n' "${paths[@]}"
            echo "EOF"
            echo "has-lock=true"
          } >> "$GITHUB_OUTPUT"
        else
          echo "has-lock=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Set up Node.js (cached)
      if: ${{ steps.node-lock.outputs.has-lock == 'true' }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm
        cache-dependency-path: ${{ steps.node-lock.outputs.paths }}

    - name: Set up Node.js
      if: ${{ steps.node-lock.outputs.has-lock != 'true' }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Cache Composer dependencies
      if: ${{ inputs.composer-install == 'true' }}
      uses: actions/cache@v4
      with:
        path: |
          ${{ inputs.working-directory }}/vendor
          ~/.composer/cache
        key: >-
          composer-${{ runner.os }}-${{ inputs.php-version }}-${{
          hashFiles(format('{0}/composer.lock', inputs.working-directory)) }}${{
          inputs.composer-cache-key }}
        restore-keys: |
          composer-${{ runner.os }}-

    - name: Install Composer dependencies
      if: ${{ inputs.composer-install == 'true' }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        set -eo pipefail
        composer install ${{ inputs.composer-args }}

    - name: Install Node dependencies
      if: ${{ inputs.npm-install == 'true' }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        NODE_LOCK_HAS_LOCK: ${{ steps.node-lock.outputs.has-lock }}
        NPM_INSTALL_COMMAND: ${{ inputs.npm-install-command }}
      run: |
        set -eo pipefail
        if [[ -f package.json ]]; then
          if [[ "${NODE_LOCK_HAS_LOCK}" != 'true' && "${NPM_INSTALL_COMMAND}" == npm\ ci* ]]; then
            echo "No npm lockfile found; falling back to 'npm install'."
            npm install
          else
            eval "${NPM_INSTALL_COMMAND}"
          fi
        else
          echo "package.json not found; skipping Node install step."
        fi

    - name: Run PHPCS
      if: ${{ inputs.run-phpcs == 'true' }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        set -eo pipefail

        declare -a cmd=("${{ inputs.phpcs-bin }}")

        if [[ -n "${{ inputs.phpcs-standard }}" ]]; then
          cmd+=("--standard=${{ inputs.phpcs-standard }}")
        fi

        if [[ -n "${{ inputs.phpcs-args }}" ]]; then
          cmd+=(${{ inputs.phpcs-args }})
        fi

        if [[ -n "${{ inputs.phpcs-paths }}" ]]; then
          cmd+=(${{ inputs.phpcs-paths }})
        fi

        "${cmd[@]}"

    - name: Run ESLint
      if: ${{ inputs.run-eslint == 'true' }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        set -eo pipefail

        read -r -a eslint_cmd <<< "${{ inputs.eslint-bin }}"
        read -r -a eslint_args <<< "${{ inputs.eslint-args }}"
        read -r -a eslint_paths <<< "${{ inputs.eslint-paths }}"

        if (( ${#eslint_paths[@]} == 0 )); then
          eslint_paths=(.)
        fi

        no_error_set=false
        for arg in "${eslint_args[@]}"; do
          if [[ "$arg" == '--no-error-on-unmatched-pattern' ]]; then
            no_error_set=true
            break
          fi
        done

        if [[ "$no_error_set" == false ]]; then
          eslint_args+=(--no-error-on-unmatched-pattern)
        fi

        "${eslint_cmd[@]}" "${eslint_args[@]}" "${eslint_paths[@]}"

    - name: Run Stylelint
      if: ${{ inputs.run-stylelint == 'true' }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        set -eo pipefail

        read -r -a stylelint_cmd <<< "${{ inputs.stylelint-bin }}"
        read -r -a stylelint_args <<< "${{ inputs.stylelint-args }}"
        read -r -a stylelint_paths <<< "${{ inputs.stylelint-paths }}"

        if (( ${#stylelint_paths[@]} == 0 )); then
          stylelint_paths=(.)
        fi

        allow_empty=false
        for arg in "${stylelint_args[@]}"; do
          if [[ "$arg" == '--allow-empty-input' ]]; then
            allow_empty=true
            break
          fi
        done

        if [[ "$allow_empty" == false ]]; then
          stylelint_args+=(--allow-empty-input)
        fi

        "${stylelint_cmd[@]}" "${stylelint_args[@]}" "${stylelint_paths[@]}"
